complaints = [
    # Water (20)
    "There is no water supply in our street for 3 days",
    "Water tank in our area is completely dry",
    "No water coming from the tap since morning",
    "Drinking water is not available in our locality",
    "Water pipeline burst near our house",
    "Water is contaminated and smells bad",
    "Bore well has stopped working in our village",
    "Water supply timing is very irregular here",
    "Leakage in the main water pipe near the park",
    "We have not received water tanker this week",
    "Low water pressure in taps every morning",
    "Water contamination causing illness in our area",
    "Our colony has had zero water for four days",
    "The water tastes and smells strange lately",
    "Municipal water supply has been cut off suddenly",
    "Pipe leakage wasting a lot of water daily",
    "No water in the tank since yesterday evening",
    "Water tanker did not arrive as scheduled",
    "Taps are completely dry in our building",
    "Irregular water supply is affecting daily life here",

    # Electricity (20)
    "Streetlight has been broken for a week",
    "Power cut in our area since yesterday",
    "Electric pole is leaning and looks dangerous",
    "Frequent power fluctuations damaging appliances",
    "No electricity in our street for 6 hours",
    "Transformer near our house is making loud noise",
    "Electric wires are hanging dangerously low",
    "Meter reading seems incorrect this month",
    "Power supply keeps tripping every few minutes",
    "Streetlights are not working in the entire lane",
    "Sudden voltage spike damaged our television",
    "Electric pole fell down after the storm",
    "There has been no power since this afternoon",
    "Our street light pole is sparking at night",
    "Current fluctuation burnt out our refrigerator",
    "Electricity bill amount seems abnormally high",
    "Power outage lasting several hours every day",
    "Exposed electric wire near the bus stop is unsafe",
    "Transformer blew up and area lost power",
    "Voltage is too low to run any appliances",

    # Sanitation (20)
    "Garbage has not been collected in our area",
    "Dustbins are overflowing near the market",
    "Sewage water is flooding the street",
    "Drainage is blocked causing bad smell",
    "Public toilet in our area is very unclean",
    "Waste is dumped illegally behind our colony",
    "Mosquito breeding due to stagnant sewage water",
    "Garbage truck has not come for two weeks",
    "Open drain near school is a health hazard",
    "Community toilet has no water or cleaning",
    "Dead animal lying uncollected on the roadside",
    "Plastic waste burning causing air pollution nearby",
    "Trash has been piling up on our street corner",
    "Sewer line is overflowing onto the road",
    "Public restroom has not been cleaned in days",
    "Foul smell coming from the blocked drain",
    "Waste collection vehicle skipped our street again",
    "Stray garbage attracting flies and rodents",
    "Sanitation workers have not visited this month",
    "Clogged sewer causing dirty water on the street",

    # Road (20)
    "There is a huge pothole on the main road",
    "Road near our house is completely broken",
    "Street road has not been repaired for months",
    "Road construction debris is blocking the path",
    "Speed breaker is damaged and causing accidents",
    "Road caved in after the recent rains",
    "No streetlights along the newly built road",
    "Footpath is broken making walking difficult",
    "Traffic signal at the junction is not working",
    "Road divider is damaged near the bus stop",
    "Manhole cover missing on the main street",
    "Newly laid road already has cracks",
    "Potholes are causing frequent traffic jams here",
    "Road surface has completely worn away",
    "Broken pavement is a hazard for pedestrians",
    "Construction work left the road unusable",
    "Road markings have faded and are barely visible",
    "Damaged flyover section needs urgent repair",
    "Uneven road surface is causing bike accidents",
    "Road has not been resurfaced in years",
]

categories = (
    ["water"] * 20 +
    ["electricity"] * 20 +
    ["sanitation"] * 20 +
    ["road"] * 20
)